server:
  port: 10086

spring:
  datasource:
    primary:
      url: jdbc:oracle:thin:@localhost:1522:XE
      username: username
      password: password
      driver-class-name: oracle.jdbc.OracleDriver
      druid:
        initial-size: 5
        min-idle: 5
        max-active: 20
        filters: stat,wall,log4j
    secondary:
      url: jdbc:mysql://localhost:3306/database?serverTimezone=Asia/Shanghai
      username: username
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
      druid:
        initial-size: 5
        min-idle: 5
        max-active: 20
        filters: stat,wall,log4j



mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: org.ashe.entity
  global-config:
    db-config:
      id-type: auto